### PR TITLE
Set a default namespace to improve auto-linkify

### LINKED ISSUE #522: AutoLinkify linking the Wrong `join` Method in Awaitables guide
It's linking to `HH\Lib\Str\join` instead of `HH\Asio\join` in:
https://docs.hhvm.com/hack/async/awaitables

Do we need to fix the priority namespaces in:

https://github.com/hhvm/user-documentation/blob/master/src/markdown-extensions/AutoLinkifyInline.php#L71-L78

### PR DESCRIPTION
**Pull request by kevinastone**
Add support for a metadata field to specify the default namespace for a block to keep short code references but allow the auto-linker to resolve the correct reference.

Fixes #522

### CODE REVIEW

File: src/typedefs.php [hunk 1]
```diff
@@ -37,6 +37,7 @@
   ?'fbonly messages' => vec<string>,
   ?'min-versions' => dict<RequirableProduct, string>,
   ?'experimental' => bool,
+  ?'default_namespace' => string,
```
Comment (fredemmott) [inline src/typedefs.php]: thanks just a nit: please replace underscore with space for consistency with `fbonly messages`; I see that I messed up and `min-versions` is already inconsistent, but let's not add a third way

Comment (fredemmott) [reply src/typedefs.php]: inherited from when this actually was yaml :p I'd also be happy for all of these to be changed to something else, I don't have any strong preference as long as they're consistent :)

Comment (kevinastone) [reply src/typedefs.php]: Agreed.  I just renamed it to `namespace` to avoid this :)
